### ISSUE TITLE
Add features provided by k8s.io/apimachinery/pkg/util/wait

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/backon#10]
https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait

**Comment by Xuanwo** [comment]
There are so many functions provided by `wait`

@weihanglo, can you help point out which features you most wanted? Many thanks for considering my request.

**Comment by weihanglo** [comment]
Since this package is called `backon`, maybe we can start from defining a trait similar to [`BackoffManager`](https://github.com/kubernetes/apimachinery/blob/276a8a7530a30f42c82b1f0fa2261a905130bf97/pkg/util/wait/wait.go#L310-L317) and then implement `backoff_until` or else. However, IIRC the public interface in `wait` package are just wrappers of some basic ones, so you might end up implementing the fundamental types.

Anyway, you are the project owner. It's up to you 😆

**Comment by Xuanwo** [comment]
Thanks for the advice, we are on the way!
